version: 1.0.0.{build}
os: Visual Studio 2017

environment:
  nodejs_version: "9.3.0"

configuration: Release

services:
  - mssql2017

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - cmd: build.bat

test: off

artifacts:
  - path: '*Client*.zip'
    name: Client
  - path: '*Service*.zip'
    name: Service
  - path: '*.dacpac'
    name: Database

deploy:
  - provider: SqlDatabase
    artifact: Database
    connection_string: 'Server=(local)\SQL2017;Database=InstructorIQ;User ID=sa;Password=Password12!'


