version: 1.0.0.{build}
os: Visual Studio 2017

environment:
  nodejs_version: "9.3.0"

configuration: Release

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - cmd: build.bat
  
test: off

artifacts:
  - path: '*.zip'


