version: 1.0.0.{build}
os: Visual Studio 2017

environment:
  nodejs_version: "9.3.0"
  ASPNETCORE_ENVIRONMENT: appveyor

configuration: Release

services:
  - mssql2016

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version

build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: 'build\*.zip'
    name: Archive
  - path: 'build\*.nupkg'
    name: Deploy
  - path: 'build\database\*.dacpac'
    name: Database

deploy:
  - provider: SqlDatabase
    artifact: Database
    connection_string: 'Server=(local)\SQL2016;Database=InstructorIQ;Integrated security=SSPI;'
    block_on_possible_data_loss: false

after_deploy:
  - cmd: dotnet test service\test\InstructorIQ.Core.Tests\InstructorIQ.Core.Tests.csproj